name: brennenadamsphotography
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /
    build_command: npm ci && npm run build
    run_command: npm start
    build_cache:
      paths:
        - node_modules/
        - .next/cache/
        - .yarn/cache/
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
